### ISSUE TITLE
Add a figure for AWS architecture

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/mg7#91]
Using https://aws.amazon.com/architecture/icons/.

**Comment by laughedelic** [comment]
Check https://github.com/ohnosequences/loquat/issues/63

**Comment by laughedelic** [comment]
Here's a draft:

[![mg7 pipeline](https://cloud.githubusercontent.com/assets/766656/17818788/528fcba0-6645-11e6-94e1-a630adcb42c1.png)](https://cloudcraft.co/view/88833129-808b-4555-970f-eb614e980398?key=mPVGc2eNWrHuwY6XijgHBQ)

Comments:

- the whole pipeline consists of several steps each of which is a _loquat_ (see diagram in https://github.com/ohnosequences/loquat/issues/63, I'll add it here later)
- each step is independently scalable: you can configure type and number of workers you want to use
- _split_, _merge_ and _counting_ loquat "sizes" should be proportional to the number of input samples
- _BLAST_ and _assignment_ loquat "sizes" should be proportional to the sizes of the samples (i.e. number of chunks after _split_) 
- this allows to analyse data as fast as you ~~are ready to pay~~ want: the most resource-demanding part is heavily parallelized

@ohnosequences/docs What do you think?

Other things that could be added to this diagram:
- example instance types (some steps require average hardware, others — more powerful)
- user interaction (launching each step, uploading input data, getting results). I didn't add it because it clutters the diagram quite a lot and it's more about data flow
- Flash step for illumina reads. It just doesn't fit 😅  and it's not clear how to show that it's optional. I would just explain it in text, because it's not a part of the core MG7 pipeline, more like a data preparation step.
